// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Pirate.Shared.Index;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Utility;

namespace Content.Pirate.Client.Index;

[GenerateTypedNameReferences]
public sealed partial class IndexAdminMenuWindow : DefaultWindow
{
    public Action<string>? OnSendPrescription;
    public Action<int>? OnAddKarma;
    public Action<int>? OnRemoveKarma;
    public Action<bool>? OnGuaranteeFpoon;

    [Dependency] private readonly IResourceCache _resourceCache = default!;

    private static readonly ResPath IndexLogoPath = new("/Textures/_Pirate/Interface/Misc/index_logo.rsi");

    public IndexAdminMenuWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        IndexLogo.Texture = _resourceCache.GetResource<RSIResource>(IndexLogoPath).RSI["index_logo"].Frame0;

        SendButton.OnPressed += _ => SendPrescription();
        PrescriptionInput.OnTextEntered += _ => SendPrescription();

        AddOneButton.OnPressed += _ => OnAddKarma?.Invoke(1);
        AddFiveButton.OnPressed += _ => OnAddKarma?.Invoke(5);
        RemoveOneButton.OnPressed += _ => OnRemoveKarma?.Invoke(1);
        RemoveFiveButton.OnPressed += _ => OnRemoveKarma?.Invoke(5);

        FpoonButton.OnToggled += args => OnGuaranteeFpoon?.Invoke(args.Pressed);
    }

    private void SendPrescription()
    {
        var text = PrescriptionInput.Text.Trim();
        if (string.IsNullOrEmpty(text))
            return;

        OnSendPrescription?.Invoke(text);
        PrescriptionInput.Text = string.Empty;
    }

    public void UpdateState(IndexAdminBoundUserInterfaceState state)
    {
        KarmaLabel.Text = Loc.GetString("index-karma-label", ("karma", state.KarmicConsequence));
        MemberNameLabel.Text = state.HasMember
            ? Loc.GetString("index-admin-member-label", ("name", state.MemberName))
            : Loc.GetString("index-admin-no-member");

        if (FpoonButton.Pressed != state.NextWeaponFpoon)
            FpoonButton.Pressed = state.NextWeaponFpoon;
    }
}
