// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client.Humanoid;
using Content.Shared._Pirate.SlimeMorph;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Enums;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using static Content.Client.Stylesheets.StylesheetHelpers;

namespace Content.Client._Pirate.SlimeMorph;

[GenerateTypedNameReferences]
public sealed partial class SlimeMorphWindow : DefaultWindow
{
    public Action<(MarkingCategories category, int slot, string id)>? OnMarkingSelected;
    public Action<(MarkingCategories category, int slot, Marking marking)>? OnMarkingColorChanged;
    public Action<MarkingCategories>? OnMarkingSlotAdded;
    public Action<(MarkingCategories category, int slot)>? OnMarkingSlotRemoved;

    public Action<Color>? OnSkinColorChanged;
    public Action<Color>? OnEyeColorChanged;
    public Action<Sex>? OnSexChanged;
    public Action<Gender>? OnGenderChanged;
    public Action<float>? OnHeightChanged;
    public Action<float>? OnWidthChanged;

    public Action<NetEntity?>? OnSelectTarget;
    public Action? OnMimic;
    public Action<NetEntity>? OnForget;
    public Action? OnRevert;
    public Action? OnApply;
    public Action? OnReset;

    private static readonly Color FontDefault = Color.FromHex("#E6E8EE");
    private static readonly Color FontDanger = Color.FromHex("#EDA393");

    private const string BtnClass = "SlimeMorphBtn";
    private const string BtnDangerClass = "SlimeMorphBtnDanger";
    private const string OptionItemClass = "SlimeMorphOption";
    private static bool _stylesInstalled;

    private readonly IEntityManager _entManager;
    private readonly HumanoidAppearanceSystem _humanoidSystem;
    private readonly MarkingManager _markingManager;

    private readonly SingleMarkingPicker[] _pickers;
    private bool _updating;
    private NetEntity? _selected;
    private EntityUid? _preview;
    private SlimeMorphUiState? _state;

    public SlimeMorphWindow()
    {
        RobustXamlLoader.Load(this);

        _entManager = IoCManager.Resolve<IEntityManager>();
        _markingManager = IoCManager.Resolve<MarkingManager>();
        _humanoidSystem = _entManager.System<HumanoidAppearanceSystem>();

        _pickers = new[] { HairPicker, FacialHairPicker, HeadSidePicker, TailPicker, ChestPicker };
        foreach (var picker in _pickers)
        {
            var category = picker.Category;
            picker.OnMarkingSelect += args =>
            {
                OnMarkingSelected?.Invoke((category, args.slot, args.id));
                PreviewMarkingSelect(category, args.slot, args.id);
            };
            picker.OnColorChanged += args =>
            {
                OnMarkingColorChanged?.Invoke((category, args.slot, args.marking));
                PreviewMarkingColor(category, args.slot, args.marking);
            };
            picker.OnSlotAdd += () => OnMarkingSlotAdded?.Invoke(category);
            picker.OnSlotRemove += slot => OnMarkingSlotRemoved?.Invoke((category, slot));
        }

        SkinColorSelector.OnColorChanged += color =>
        {
            if (_updating)
                return;
            OnSkinColorChanged?.Invoke(color);
            PreviewField(s => s.SkinColor = color);
        };
        EyeColorSelector.OnColorChanged += color =>
        {
            if (_updating)
                return;
            OnEyeColorChanged?.Invoke(color);
            PreviewField(s => s.EyeColor = color);
        };

        InstallStyles();
        SexButton.OptionStyleClasses.Add(OptionItemClass);
        GenderButton.OptionStyleClasses.Add(OptionItemClass);

        foreach (var sex in Enum.GetValues<Sex>())
            SexButton.AddItem(Loc.GetString($"humanoid-profile-editor-sex-{sex.ToString().ToLower()}-text"), (int) sex);
        SexButton.OnItemSelected += args =>
        {
            SexButton.SelectId(args.Id);
            if (_updating)
                return;
            OnSexChanged?.Invoke((Sex) args.Id);
            PreviewField(s => s.Sex = (Sex) args.Id);
        };

        foreach (var gender in Enum.GetValues<Gender>())
            GenderButton.AddItem(Loc.GetString($"slime-morph-gender-{gender.ToString().ToLower()}"), (int) gender);
        GenderButton.OnItemSelected += args =>
        {
            GenderButton.SelectId(args.Id);
            if (_updating)
                return;
            OnGenderChanged?.Invoke((Gender) args.Id);
            PreviewField(s => s.Gender = (Gender) args.Id);
        };

        HeightSlider.OnValueChanged += _ =>
        {
            HeightValue.Text = HeightSlider.Value.ToString("0.00");
            if (_updating)
                return;
            OnHeightChanged?.Invoke(HeightSlider.Value);
            PreviewField(s => s.Height = HeightSlider.Value);
        };
        WidthSlider.OnValueChanged += _ =>
        {
            WidthValue.Text = WidthSlider.Value.ToString("0.00");
            if (_updating)
                return;
            OnWidthChanged?.Invoke(WidthSlider.Value);
            PreviewField(s => s.Width = WidthSlider.Value);
        };

        RememberedList.OnItemSelected += _ => OnListSelectionChanged();
        RememberedList.OnItemDeselected += _ => OnListSelectionChanged();

        MimicButton.OnPressed += _ => OnMimic?.Invoke();
        ForgetButton.OnPressed += _ =>
        {
            if (_selected is { } target)
                OnForget?.Invoke(target);
        };
        RevertButton.OnPressed += _ => OnRevert?.Invoke();
        ApplyButton.OnPressed += _ => OnApply?.Invoke();
        ResetButton.OnPressed += _ => OnReset?.Invoke();

        RestyleButtons();
    }

    private void OnListSelectionChanged()
    {
        if (_updating)
            return;

        _selected = RememberedList.GetSelected().FirstOrDefault()?.Metadata as NetEntity?;
        ForgetButton.Disabled = _selected == null;
        OnSelectTarget?.Invoke(_selected);
    }

    public void UpdateState(SlimeMorphUiState state)
    {
        _state = state;
        _updating = true;

        SexButton.SelectId((int) state.Sex);
        GenderButton.SelectId((int) state.Gender);
        SkinColorSelector.Color = state.SkinColor;
        EyeColorSelector.Color = state.EyeColor;

        HeightSlider.MinValue = state.MinHeight;
        HeightSlider.MaxValue = state.MaxHeight;
        HeightSlider.Value = state.Height;
        HeightValue.Text = state.Height.ToString("0.00");

        WidthSlider.MinValue = state.MinWidth;
        WidthSlider.MaxValue = state.MaxWidth;
        WidthSlider.Value = state.Width;
        WidthValue.Text = state.Width.ToString("0.00");

        foreach (var picker in _pickers)
        {
            var category = picker.Category;
            var markings = state.MarkingSet.TryGetCategory(category, out var list)
                ? new List<Marking>(list)
                : new List<Marking>();
            var total = state.MarkingSet.PointsLeft(category) + markings.Count;
            picker.UpdateData(markings, state.Species, total);
        }

        UpdateRemembered(state);

        ApplyButton.Disabled = !state.CanApply;
        MimicButton.Disabled = !state.CanMimic;

        UpdatePreview(state);
        RestyleButtons();

        _updating = false;
    }

    private void UpdateRemembered(SlimeMorphUiState state)
    {
        RememberedList.Clear();

        foreach (var appearance in state.Remembered)
        {
            var item = RememberedList.AddItem(Loc.GetString("slime-morph-remembered-entry",
                ("name", appearance.Name),
                ("species", _humanoidSystem.GetSpeciesRepresentation(appearance.Species))));
            item.Metadata = appearance.Target;
            if (state.SelectedTarget == appearance.Target)
                item.Selected = true;
        }

        _selected = state.SelectedTarget;
        ForgetButton.Disabled = _selected == null;
    }

    // ---- Live preview ----

    private void PreviewField(Action<SlimeMorphUiState> mutate)
    {
        if (_state == null)
            return;

        mutate(_state);
        UpdatePreview(_state);
    }

    private void PreviewMarkingColor(MarkingCategories category, int slot, Marking marking)
    {
        if (_updating || _state == null
            || !_state.MarkingSet.TryGetCategory(category, out var list)
            || slot < 0 || slot >= list.Count)
            return;

        for (var i = 0; i < list[slot].MarkingColors.Count && i < marking.MarkingColors.Count; i++)
            list[slot].SetColor(i, marking.MarkingColors[i]);

        UpdatePreview(_state);
    }

    private void PreviewMarkingSelect(MarkingCategories category, int slot, string id)
    {
        if (_updating || _state == null
            || !_markingManager.Markings.TryGetValue(id, out var proto)
            || !_state.MarkingSet.TryGetCategory(category, out var list)
            || slot < 0 || slot >= list.Count)
            return;

        var marking = proto.AsMarking();
        for (var i = 0; i < marking.MarkingColors.Count && i < list[slot].MarkingColors.Count; i++)
            marking.SetColor(i, list[slot].MarkingColors[i]);

        _state.MarkingSet.Replace(category, slot, marking);
        UpdatePreview(_state);
    }

    private void UpdatePreview(SlimeMorphUiState state)
    {
        if (_preview is not { } preview || _entManager.Deleted(preview))
        {
            preview = _entManager.Spawn("MobSlimePersonDummy");
            _preview = preview;
            Preview.SetEntity(preview);
        }

        if (!_entManager.TryGetComponent<HumanoidAppearanceComponent>(preview, out var comp)
            || !_entManager.TryGetComponent<SpriteComponent>(preview, out var sprite))
            return;

        comp.MarkingSet = new MarkingSet(state.MarkingSet);
        comp.EyeColor = state.EyeColor;
        comp.Sex = state.Sex;
        comp.Gender = state.Gender;
        comp.Height = state.Height;
        comp.Width = state.Width;

        _humanoidSystem.SetSkinColor(preview, state.SkinColor, false);

        // Mirror the head base-sprite override (baked muzzles etc.) so the preview matches.
        if (state.HeadLayer is { } headLayer)
        {
            var f = state.HeadColorFactor;
            var headColor = new Color(
                state.SkinColor.R * f,
                state.SkinColor.G * f,
                state.SkinColor.B * f,
                state.SkinColor.A * state.HeadColorAlpha);
            _humanoidSystem.SetBaseLayerId(preview, HumanoidVisualLayers.Head, headLayer, false);
            _humanoidSystem.SetBaseLayerColor(
                preview,
                HumanoidVisualLayers.Head,
                headColor,
                false);
        }
        else
        {
            comp.CustomBaseLayers.Remove(HumanoidVisualLayers.Head);
        }

        _humanoidSystem.UpdateSprite((preview, comp, sprite));
    }

    // ---- Button / selector styling ----

    /// <summary>
    /// Tag every button in the window with our style classes so the installed rules (with hover /
    /// pressed states) apply, and add small padding around the color-channel spinboxes.
    /// </summary>
    private void RestyleButtons()
    {
        ClassifyControls(Contents);
        RevertButton.AddStyleClass(BtnDangerClass);

        foreach (var button in new[] { ApplyButton, MimicButton, ResetButton, ForgetButton })
            button.Label.FontColorOverride = FontDefault;
        RevertButton.Label.FontColorOverride = FontDanger;
    }

    private void ClassifyControls(Control control)
    {
        foreach (var child in control.Children)
        {
            switch (child)
            {
                case ContainerButton button when !button.HasStyleClass(BtnClass):
                    button.AddStyleClass(BtnClass);
                    break;
                // Breathing room: gap before the "-" stepper and padding off the panel edge.
                case SpinBox spin:
                    spin.Margin = new Thickness(6, 0, 4, 0);
                    break;
            }

            ClassifyControls(child);
        }
    }

    /// <summary>
    /// Button/OptionButton dropdown popups live under the modal root, not this window, so a
    /// window-scoped stylesheet can't reach them. Append rules (scoped to our unique classes, with
    /// full hover/pressed/disabled states) to the global sheet once.
    /// </summary>
    private static void InstallStyles()
    {
        if (_stylesInstalled)
            return;

        var ui = IoCManager.Resolve<IUserInterfaceManager>();
        if (ui.Stylesheet is not { } sheet)
            return;

        var rules = new List<Robust.Client.UserInterface.StyleRule>(sheet.Rules);

        // Normal window buttons (raised), with hover/pressed/disabled feedback.
        AddButtonRules(rules, BtnClass,
            MakeBox("#272B35", "#383D4A"),
            MakeBox("#2E323D", "#4A505E"),
            MakeBox("#21242D", "#383D4A"),
            MakeBox("#1E2129", "#2A2E39"));

        // Destructive (Revert).
        AddButtonRules(rules, BtnDangerClass,
            MakeBox("#3A2622", "#6B3A32"),
            MakeBox("#47302B", "#7E463C"),
            MakeBox("#2E211E", "#6B3A32"),
            MakeBox("#241A18", "#3A2622"));

        // Dropdown popup items.
        AddButtonRules(rules, OptionItemClass,
            MakeBox("#21242D", "#2E323D"),
            MakeBox("#272B35", "#383D4A"),
            MakeBox("#24344A", "#6F9FE0"),
            MakeBox("#1E2129", "#2A2E39"));

        ui.Stylesheet = new Robust.Client.UserInterface.Stylesheet(rules);
        _stylesInstalled = true;
    }

    private static void AddButtonRules(List<Robust.Client.UserInterface.StyleRule> rules, string styleClass,
        StyleBoxFlat normal, StyleBoxFlat hover, StyleBoxFlat pressed, StyleBoxFlat disabled)
    {
        rules.Add(E<ContainerButton>().Class(styleClass).Pseudo(ContainerButton.StylePseudoClassNormal)
            .Box(normal).Modulate(Color.White));
        rules.Add(E<ContainerButton>().Class(styleClass).Pseudo(ContainerButton.StylePseudoClassHover)
            .Box(hover).Modulate(Color.White));
        rules.Add(E<ContainerButton>().Class(styleClass).Pseudo(ContainerButton.StylePseudoClassPressed)
            .Box(pressed).Modulate(Color.White));
        rules.Add(E<ContainerButton>().Class(styleClass).Pseudo(ContainerButton.StylePseudoClassDisabled)
            .Box(disabled).Modulate(Color.White));
    }

    private static StyleBoxFlat MakeBox(string background, string border)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(background),
            BorderColor = Color.FromHex(border),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 14,
            ContentMarginRightOverride = 14,
            ContentMarginTopOverride = 6,
            ContentMarginBottomOverride = 6,
        };
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (!disposing)
            return;

        if (_preview is { } preview && !_entManager.Deleted(preview))
            _entManager.DeleteEntity(preview);
        _preview = null;
    }
}
